version: '2.1'
services:
  janus-gateway:
    image: 'canyan/janus-gateway:0.10.7'
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    ports:
      - "8088:8088"
      - "8089:8089"
      - "8889:8889"
      - "8000:8000"
      - "7088:7088"
      - "7089:7089"
    volumes:
      - "./janus/etc/janus:/usr/local/etc/janus"
      - "./janus/recordings:/opt/janus/share/janus/recordings/binary"
      - "./janus/log/:/usr/local/log/"
    restart: always