version: '2.1'
services:
  janus-gateway:
    image: 'canyan/janus-gateway:0.10.7'
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    #ports:
      #- "8088:8088"
      #- "8089:8089"
      #- "7088:7088"
      #- "7089:7089"
    volumes:
      - "./janus/etc/janus:/usr/local/etc/janus"
      - "./janus/recordings:/opt/janus/share/janus/recordings/binary"
      - "./janus/log/:/usr/local/log/"
  
  app:
    build: .
    volumes:
      - ".:/app"
  
  nginx:
    build:
      context: ./nginx
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ./nginx/logs/:/var/log/nginx
      - ./nginx/sites:/etc/nginx/sites-available
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"